### PR TITLE
fix(config): wire obfuscation to apm_config path; add blacklist alias (#1480 issues 2+3)

### LINKED ISSUE #1480: config: three schema deviations in ADP that may be bugs
Three places in the config key registry expose schema incompatibilities between the Agent and ADP that need investigation. All three were surfaced while building the config smoke tests in #1457.

---

### 1. `enable_payloads.*` — flat vs. nested field naming

**Code:** https://github.com/DataDog/saluki/pull/1457#discussion_r3139962787
**File:** \`lib/saluki-components/src/config_registry/datadog/dogstatsd.rs\`

The Agent schema defines these as nested properties: \`enable_payloads.events\`, \`enable_payloads.series\`, \`enable_payloads.service_checks\`, \`enable_payloads.sketches\` (see \`ENABLE_PAYLOADS_EVENTS\` etc. in \`generated/schema.rs\`).

ADP's \`DogStatsDConfiguration\` declares them as flat underscore-separated fields with no \`#[serde(rename)]\`: \`enable_payloads_events\`, \`enable_payloads_series\`, etc. The two naming conventions are incompatible at the config-loader level — an Agent config file that sets \`enable_payloads.events: false\` produces a nested object that the flat field cannot consume, and the value is silently ignored.

**Fix:** Either rename the struct fields to use \`#[serde(rename = "enable_payloads.events")]\` etc., or add a \`#[serde(flatten)]\` sub-struct that mirrors the Agent's nested \`enable_payloads\` section.

---

### 2. Trace obfuscation config path prefix mismatch

**Code:** https://github.com/DataDog/saluki/pull/1457#discussion_r3139970331
**File:** \`lib/saluki-components/src/config_registry/datadog/trace_obfuscation.rs\`

The Agent schema defines obfuscation keys under \`apm_config.obfuscation.*\` (e.g. \`apm_config.obfuscation.credit_cards.enabled\`). See \`APM_CONFIG_OBFUSCATION_*\` constants in \`generated/schema.rs\`.

\`TraceObfuscationConfiguration\` contains a \`config: ObfuscationConfig\` field, so \`cfg.as_typed::<TraceObfuscationConfiguration>()\` reads from \`config.*\` paths, not \`apm_config.obfuscation.*\`. This means the struct is effectively unreachable via the Agent's documented config keys unless the caller goes through \`from_apm_configuration\` (which does read from \`apm_config.obfuscation.*\` and populates the struct correctly).

**Fix:** Evaluate whether \`TraceObfuscationConfiguration\` should be wired to deserialize directly from \`apm_config.obfuscation.*\` so it works consistently regardless of which constructor is used.

---

### 3. `statsd_metric_namespace_blacklist` → `blocklist` — silent config drop

**Code:** https://github.com/DataDog/saluki/pull/1457#discussion_r3139976003
**File:** \`lib/saluki-components/src/config_registry/datadog/dogstatsd_prefix_filter.rs\`

ADP renamed \`statsd_metric_namespace_blacklist\` to \`statsd_metric_namespace_blocklist\` for inclusive language, but the struct field has **no \`#[serde(alias)\`** for the old spelling. An Agent config file that customizes \`statsd_metric_namespace_blacklist\` will be silently ignored by ADP — the customized namespace exclusion list is dropped and ADP falls back to the hardcoded default.

The default lists happen to be identical today, so this only affects users who have customized the key. It is a silent data-loss bug for any such user.

**Fix:** Add \`#[serde(alias = "statsd_metric_namespace_blacklist")]\` to the \`metric_prefix_blocklist\` field in \`transforms/dogstatsd_prefix_filter/mod.rs\`. This is a one-line fix with no risk.

---

All three are tracked in the annotation files with `TODO` comments pointing here.

### PR DESCRIPTION
**Pull request by thieman**
## Summary

Fixes issues 2 and 3 from #1480. Issue 1 was fixed in #1515.

**Issue 2 — Trace obfuscation config path prefix mismatch:**
- `TraceObfuscationConfiguration.from_configuration` was reading from `config.*` paths instead of the Agent's `apm_config.obfuscation.*` paths. It now delegates to `from_apm_configuration`.
- Annotations updated to reference generated `APM_CONFIG_OBFUSCATION_*` schema entries with correct YAML paths.
- `DD_APM_OBFUSCATION_*` env vars (which Figment produces as flat keys without the `_config_` segment) are now wired up via 25 `KEY_ALIASES` entries. `ObfuscationConfig` deserializes directly from those flat keys using `#[serde(flatten)]` on each sub-struct field and flat `apm_obfuscation_*` serde renames on each sub-struct's fields. No intermediate copy or conversion struct needed.

**Issue 3 — `statsd_metric_namespace_blacklist` → silent config drop:**
- `DogStatsDPrefixFilterConfiguration.metric_prefix_blocklist` had no `#[serde(alias)]` for the Agent's original `statsd_metric_namespace_blacklist` spelling, silently dropping customized namespace exclusion lists.
- Added `alias = "statsd_metric_namespace_blacklist"` and updated the annotation to use the generated schema entry.

**Refactoring along the way:**
- Extracted `deserialize_space_separated_or_seq` (previously only in `proxy.rs`) to `saluki_config::space_separated`, where it sits alongside `duration_string` as a shared config deserialization utility. Added an `Option<Vec<String>>` variant.
- `ObfuscationConfig` now stores typed sub-structs as fields (`credit_cards: CreditCardObfuscationConfig`, `http: HttpObfuscationConfig`, etc.) rather than flat scalar fields. Each sub-struct carries its own flat serde renames; `#[serde(flatten)]` propagates them up. `JsonObfuscationConfig` is split into `EsObfuscationConfig` / `MongoObfuscationConfig` / `OpenSearchObfuscationConfig` so each can carry the correct rename prefix. Callers access fields directly — no accessor methods on pure data types.

## Test plan

- [ ] `cargo test -p saluki-components --lib -- trace_obfuscation` passes
- [ ] `cargo test -p saluki-components --lib -- dogstatsd_prefix_filter` passes
- [ ] CI green

Closes #1480 (issues 2 and 3)

### CODE REVIEW

File: lib/saluki-components/src/common/datadog/obfuscation.rs [hunk 1]
```diff
@@ -276,16 +165,77 @@ impl SqlObfuscationConfig {
     }
 }
 
-impl JsonObfuscationConfig {
-    pub fn enabled(&self) -> bool {
-        self.enabled
-    }
+/// Elasticsearch obfuscation configuration.
```
Comment (thieman) [inline lib/saluki-components/src/common/datadog/obfuscation.rs:168]: Changed these to be dumb structs rather than sharing `JsonObfuscationConfig` and having to call methods

File: lib/saluki-components/src/common/datadog/proxy.rs [hunk 2]
```diff
@@ -299,43 +300,6 @@ fn ip_in_cidr(network: IpAddr, prefix_len: u8, addr: IpAddr) -> bool {
     }
 }
 
-/// Deserializes a `Vec<String>` from either a sequence or a space-separated string.
```
Comment (thieman) [inline lib/saluki-components/src/common/datadog/proxy.rs:302]: This is moved into shared code in saluki-config so it can also be used by obfuscation config

File: lib/saluki-components/src/transforms/trace_obfuscation/json.rs [hunk 3]
```diff
@@ -84,31 +79,21 @@ impl JsonObfuscator {
...
-    }
-
     fn default_sql_config() -> SqlObfuscationConfig {
         SqlObfuscationConfig::default()
     }
 
     /// Helper for tests - creates obfuscator and obfuscates in one call.
     fn obfuscate_json_string(
-        json_str: &str, config: &JsonObfuscationConfig, sql_config: &SqlObfuscationConfig,
+        json_str: &str, keep_values: &[String], obfuscate_sql_values: &[String], sql_config: &SqlObfuscationConfig,
```
Comment (thieman) [inline lib/saluki-components/src/transforms/trace_obfuscation/json.rs:88]: [Claude Sonnet 4.6] The changes in `lib/saluki-components/src/transforms/trace_obfuscation/json.rs` are purely mechanical test updates driven by a 4-line production signature change.

**Production change:** `JsonObfuscator::new` previously took `config: &JsonObfuscationConfig`. Since `JsonObfuscationConfig` was split into three separate types (`EsObfuscationConfig`, `MongoObfuscationConfig`, `OpenSearchObfuscationConfig`) so each can carry its own flat serde rename prefix, the constructor now takes the two relevant slices directly:

```rust
// before
pub fn new(config: &JsonObfuscationConfig, sql_config: &SqlObfuscationConfig)

// after
pub fn new(keep_values: &[String], obfuscate_sql_values: &[String], sql_config: &SqlObfuscationConfig)
```

**Test changes:** The tests had a helper `obfuscate_json_string(json, &config, &sql_config)` that built a `JsonObfuscationConfig` struct literal and passed it in. With the new signature each call site becomes `obfuscate_json_string(json, keep_values, obfuscate_sql_values, &sql_config)`. Every change is a mechanical substitution of the same values — no test logic, inputs, or assertions were modified.

**Review by tobz — APPROVED** [review]
